config/routes.rb
Rails.application.routes.draw do
	resources :providers
	resources :banks
  	devise_for :users
  	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  	# Defines the root path route ("/")
	root "home#index"

	get "home/dashboard"
end

app/models/provider.rb
# == Schema Information
#
# Table name: providers
#
#  id             :integer          not null, primary key
#  name           :string
#  nit            :string
#  name_contact   :string
#  phone_contact  :string
#  account_number :string
#  bank_id        :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Provider < ApplicationRecord
  	belongs_to :bank

	validates_presence_of :name, :name_contact
	validates :nit, format: { with: /(^[0-9]{9}-[0-9]{1})/ }, allow_blank: false
	validates :account_number, length: { maximum: 15}, allow_blank: true
	validates :phone_contact, length: { maximum: 10}, allow_blank: true
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: %i[ show edit update destroy ]

  # GET /providers or /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1 or /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers or /providers.json
  def create
    @provider = Provider.new(provider_params)
	@providers = Provider.order("created_at DESC")

    respond_to do |format|
      if @provider.save
		flash.now[:success] = "Proveedor fue creado con éxito."
		format.turbo_stream { 
			render turbo_stream: [
				turbo_stream.update("flash", partial: "shared/flash"),	
				turbo_stream.update('providers-table', partial: 'providers/table', locals: {providers: @providers})
			]
		}
        format.html { redirect_to provider_url(@provider), notice: "Proveedor fue creado con éxito." }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1 or /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
		flash.now[:notice] = "Proveedor se actualizó con éxito."
		format.turbo_stream {
			render turbo_stream: [
				turbo_stream.replace(@provider, partial: "providers/provider", locals: {provider: @provider}),
				turbo_stream.update("flash", partial: "shared/flash")
			]
		}
        format.html { redirect_to provider_url(@provider), notice: "Provider se actualizó con éxito." }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1 or /providers/1.json
  def destroy
    @provider.destroy

    respond_to do |format|
		flash.now[:notice] = "Proveedor fue eliminado con éxito."
		format.turbo_stream { 
			render turbo_stream: [
				turbo_stream.remove(@provider),
				turbo_stream.update("flash", partial: "shared/flash")
			]
		}
		format.html { redirect_to providers_url, notice: "Proveedor fue eliminado con éxito." }
		format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def provider_params
      params.require(:provider).permit(:name, :nit, :name_contact, :phone_contact, :account_number, :bank_id)
    end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.html.erb
<%= form_with(model: provider, class: "contents") do |form| %>
	<% if provider.errors.any? %>
		<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded justify-between mb-4">
			<h2><%= pluralize(provider.errors.count, "errores") %>:</h2>

			<ul class="text-sm list-disc pl-6">
				<% provider.errors.each do |error| %>
				<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="grid grid-cols-2 gap-4 mt-4">
		<div>
			<%= form.label :name %>
			<%= form.text_field :name, class: "field-input" %>
		</div>

		<div>
			<%= form.label :nit %>
			<%= form.text_field :nit, class: "field-input", placeholder: "901362343-4" %>
		</div>

		<div>
			<%= form.label :name_contact %>
			<%= form.text_field :name_contact, class: "field-input" %>
		</div>

		<div>
			<%= form.label :phone_contact %>
			<%= form.text_field :phone_contact, class: "field-input" %>
		</div>

		<div>
			<%= form.label :account_number %>
			<%= form.text_field :account_number, class: "field-input" %>
		</div>

		<div>
			<%= form.label :bank_id %>
			<%= form.collection_select(:bank_id, Bank.order("created_at DESC"), :id, :name, {include_blank: false}, {:multiple => false, class: "field-input"} ) %>
		</div>
	</div>
	
	<div class="mt-4">
		<%= form.submit class: "btn-primary" %>
	</div>


<% end %>

app/views/providers/_provider.html.erb
<tr id="<%= dom_id provider %>">
	<td class="table-td">
		<%= provider.name %>
	</td>

	<td class="table-td">
		<%= provider.nit %>
	</td>

	<td class="table-td">
		<%= provider.name_contact %>
	</td>

	<td class="table-td">
		<%= provider.phone_contact %>
	</td>

	<td class="table-td">
		<%= provider.account_number %>
	</td>

	<td class="table-td">
		<%= provider.bank.name %>
	</td>

	<td class="table-td table-actions">
		<%= link_to edit_provider_path(provider), data: { turbo_frame: 'modal'}, "data-test" => "edit-provider"  do %>
			<i class='bx bxs-edit text-xl text-secondary-500' ></i>
		<% end %>

		<%= link_to provider, method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" }, "data-test" => "delete-provider"  do %>	
			<i class='bx bxs-trash text-xl text-red-400' ></i>
		<% end %>
	</td>
	
</tr>

app/views/providers/_table.html.erb
<table class="table">
	<thead>
		<tr>
			<th class="table-th">Nombre</th>
			<th class="table-th">Nit</th>
			<th class="table-th">Nombre de Contacto</th>
			<th class="table-th">Teléfono de Contacto</th>
			<th class="table-th"># Cuenta</th>
			<th class="table-th">Banco</th>
			<th class="table-th">Acciones</th>
		</tr>
	</thead>
	<tbody id="providers">
		<% @providers.each do |provider| %>
			<%= render provider %>			
		<% end %>
	</tbody>
</table>

app/views/providers/edit.html.erb
<%= render "shared/modal", title: t("edit_provider") do %>
	<%= render "form", provider: @provider %>
<% end %>

app/views/providers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Providers</h1>
    <%= link_to 'New provider', new_provider_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="providers" class="min-w-full">
    <%= render @providers %>
  </div>
</div>

app/views/providers/new.html.erb
<%= render "shared/modal", title: t("new_provider") do %>
	<%= render "form", provider: @provider %>
<% end %>

app/views/providers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @provider %>

    <%= link_to 'Edit this provider', edit_provider_path(@provider), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this provider', provider_path(@provider), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to providers', providers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>