config/routes.rb
Rails.application.routes.draw do
	resources :providers
	resources :banks
  	devise_for :users
  	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  	# Defines the root path route ("/")
	root "home#index"

	get "home/dashboard"
end

app/models/bank.rb
# == Schema Information
#
# Table name: banks
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Bank < ApplicationRecord
	validates_presence_of :name
	validates :name, length: {minimum: 2, maximum: 50}, allow_blank: false

	has_many :providers, :dependent => :restrict_with_error 
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: %i[ show edit update destroy ]

  # GET /banks or /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1 or /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks or /banks.json
  def create
    @bank = Bank.new(bank_params)
	@banks = Bank.order("created_at DESC")

    respond_to do |format|
      if @bank.save
		flash.now[:success] = "Banco fue creado con éxito."
		format.turbo_stream { 
			render turbo_stream: [
				turbo_stream.update("flash", partial: "shared/flash"),	
				turbo_stream.update('banks-table', partial: 'banks/table', locals: {banks: @banks})
			]
		}
        format.html { redirect_to bank_url(@bank), notice: "Bank fue creado con éxito." }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1 or /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
		flash.now[:notice] = "Banco se actualizó con éxito."
		format.turbo_stream { 
			render turbo_stream: [
				turbo_stream.replace(@bank, partial: "banks/bank", locals: {bank: @bank}),
				turbo_stream.update("flash", partial: "shared/flash")
			]
		}
        format.html { redirect_to bank_url(@bank), notice: "Bank se actualizó con éxito." }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1 or /banks/1.json
  def destroy
	

    respond_to do |format|
		if @bank.destroy
			flash.now[:notice] = "Banco fue eliminado con éxito"
			format.turbo_stream { 
				render turbo_stream: [
					turbo_stream.remove(@bank),
					turbo_stream.update("flash", partial: "shared/flash")
				]
			}
			  format.html { redirect_to banks_url, notice: "Bank fue eliminado con éxito" }
			  format.json { head :no_content }
		else
			flash.now[:error] = "Bank cannot be deleted has associated providers"
			format.turbo_stream { 
				render turbo_stream: [
					turbo_stream.update("flash", partial: "shared/flash")
				]
			}
		end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bank_params
      params.require(:bank).permit(:name)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
		
end

app/views/banks/_bank.html.erb
<tr id="<%= dom_id bank %>">
	<td class="table-td"><%= bank.name %></td>
	<td class="table-td table-actions">
		<%= link_to edit_bank_path(bank), data: { turbo_frame: 'modal'} do %>
			<i class='bx bxs-edit text-xl text-secondary-500' ></i>
		<% end %>

		<%= link_to bank, method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" }  do %>	
			<i class='bx bxs-trash text-xl text-red-400' ></i>
		<% end %>
	</td>
</tr>

app/views/banks/_form.html.erb
<%= form_with(model: bank, class: "contents") do |form| %>
  <% if bank.errors.any? %>
		<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded justify-between mb-4">
			<h2><%= pluralize(bank.errors.count, "errores") %>: </h2>
			<ul class="text-sm list-disc pl-6">
				<% bank.errors.each do |error| %>
				<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

  	<div class="my-5">
		<%= form.label :name %>
		<%= form.text_field :name, class: "field-input" %>
  	</div>

	<div class="inline">
		<%= form.submit class: "btn-primary" %>
	</div>
<% end %>

app/views/banks/_table.html.erb
<table class="table">
	<thead>
		<tr>
			<th class="table-th">Nombre</th>
			<th class="table-th">Acciones</th>
		</tr>
	</thead>
	<tbody id="banks">
		<% @banks.each do |bank| %>
			<%= render bank %>
			
			
		<% end %>
	</tbody>
</table>

app/views/banks/edit.html.erb
<%= render "shared/modal", title: "Edit Bank" do %>
	<%= render "form", bank: @bank %>
<% end %>

app/views/banks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Banks</h1>
    <%= link_to 'New bank', new_bank_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="banks" class="min-w-full">
    <%= render @banks %>
  </div>
</div>

app/views/banks/new.html.erb
<%= render "shared/modal", title: t("new_bank") do %>
	<%= render "form", bank: @bank %>
<% end %>

app/views/banks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @bank %>

    <%= link_to 'Edit this bank', edit_bank_path(@bank), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this bank', bank_path(@bank), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to banks', banks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>