config/routes.rb
Rails.application.routes.draw do
	resources :providers
	resources :banks
  	devise_for :users
  	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  	# Defines the root path route ("/")
	root "home#index"

	get "home/dashboard"
end

app/views/shared/_flash.html.erb
<% flash.each do |flash_type, message| %>

	<div class="w-[390px] flex justify-between bg-green-200 rounded-lg border-green-300 border-2 py-4 px-6 fixed bottom-10 left-1/2 translate-x-[-50%]" data-controller="flash">
		
		<%= message %>

		<button class="" data-action="flash#dismiss">
			<i class='bx bxs-x-circle text-green-900'></i>
		</button>
	</div>
<% end %>

app/views/shared/_flash_devise.html.erb
<% flash.each do |flash_type, message| %>
	<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded flex justify-between my-2" role="alert">
		<span><%= message %></span>
		<button>
			<i class='bx bxs-x-circle'></i>
		</button>
	</div>
<% end %>

app/views/shared/_head.html.erb
<head>
    <title>HoyTrabajas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
	
	<%# Font %>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;600;700&display=swap" rel="stylesheet">

	<%# Icons %>
	<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

</head>

app/views/shared/_header.html.erb
<header class="bg-secondary-500 shadow">
	<div class="container mx-auto">
		<div class="flex justify-between items-center py-4">
			<div class="flex items-center">
				<img src="<%= asset_path("logo.svg") %>" width="200px" alt="">
				<div class="text-white ml-20 space-x-6">
					<%= link_to "Inicio", root_path %>
					<%= link_to "Dashboard", home_dashboard_path %>
				</div>
			</div>
			<div>
				<% if user_signed_in? %>
					<span class="text-white mr-2"><%= current_user.email %></span>.

					<%= link_to t("logout"), destroy_user_session_path, data: { turbo_method: :delete }, class: "btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>
</header>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
	<%= tag.div data: {  controller: "modal", turbo_modal_target: "modal", action: "turbo:submit-end->modal#submitEnd keyup@window->modal#closeWithKeyboard"} do %>
		<div  class="flex justify-center items-center bg-gray-700 backdrop-blur-[1px] bg-opacity-50  overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full h-full">
			<div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
				<!-- Modal content -->
				<div class="relative bg-white shadow">
					<!-- Modal header -->
					<div class="flex justify-between items-center p-4 rounded-t border-b ">
						<div class="modal-title h5"><%= title %> </div>
						<%= button_tag  data: { action: "modal#hideModal" }, type: "button" do %>
							<i class='bx bx-x-circle text-2xl text-secondary-500'></i>
						<% end %>
					</div>
					<!-- Modal body -->
					<div class="p-6 pt-0 space-y-6">
						<%= yield %>
					</div>
				</div>
			</div>
		</div>
	<% end %>
<% end %>